#pragma once

#include <iostream>
#include <algorithm>
#include <conio.h>
#include <exception>
#include <vector>
#include <array>
#include <thread>
//#include <span>
#include <functional>
#include <unordered_map>
#include <atomic>
#include <cassert>
#include <future>
#include <type_traits>
#include <shared_mutex>
#include <atomic>
#include <chrono>
#include <execution>
#include <random>
#include <span>
#include <ranges>
#include <map>
#include <latch>
#include <unordered_map>
#include <stack>
#include <fstream>
